<br><br><center><h1 style="font-size:2em;color:green">Lernkontrolle 31.03.2023</h1></center>
<br>
<center>Die möglichen Punkte stehen bei der jeweiligen Aufgabe dabei</center>

<div  class="alert alert-block alert-info">
1. Im Folgenden findest du drei mögliche Wege, um eine Zahlenliste von 1 bis 1.000.000 zu erzeugen. Deine Aufgabe ist es, ihre Laufzeiten zu vergleichen und zum Schluss zu sagen, welche die schnellste und welche die langsamste Methode ist. (12 Punkte)
<div\>

In [33]:
%%time
import time
zahlenliste = []
tic = time.perf_counter()
for zahl in range(1,100001):
    zahlenliste.append(zahl)
toc = time.perf_counter()
print(toc-tic)

0.007591200002934784
CPU times: total: 15.6 ms
Wall time: 7.01 ms


In [34]:
%%time
tic = time.perf_counter()
[zahl for zahl in range(1,100001)]
toc = time.perf_counter()
print(toc-tic)

0.0034975999733433127
CPU times: total: 15.6 ms
Wall time: 3.99 ms


In [35]:
%%time
tic = time.perf_counter()
list(range(1,100001))
toc = time.perf_counter()
print(toc-tic)

0.0020067000295966864
CPU times: total: 0 ns
Wall time: 1.99 ms


<div  class="alert alert-block alert-info">
2. Schreibe eine try&except-Bedingung. In dem try soll Code stehen, mit dem ein Ordner auf deinem Desktop erzeugt wird (Verwende hierzu einen absoluten Pfad). In dem except soll eine Meldung stehen, dass der Ordner bereits existiert. Führe den Code zwei Mal aus! (6 Punkte)

    Output:
    print("Der Ordner existiert bereits!")

</div>

In [36]:
import os

try:
    os.mkdir(r"C:/Users/pasca/Desktop/Aufgabe7")
except:
    print("Der Ordner existiert bereits!")

Der Ordner existiert bereits!


<div  class="alert alert-block alert-info">
3. Schreibe eine try&except-Bedingung. In dem try soll Code stehen, mit dem ein Ordner auf deinem Desktop erzeugt wird (Verwende hierzu einen absoluten Pfad). Dieses Mal soll es aber zwei verschiedene except Bedingungen für folgende Fälle geben:

   1. Wenn es den Ordner bereits gibt.
   2. Wenn der eingegebene Pfad nicht stimmt.


    Output:
    print("Der Ordner existiert bereits!")

(6 Punkte)
</div>

In [37]:
try:
    os.mkdir(r"C:/Users/pasca/Desktop/Aufgabe8")
except FileExistsError:
    print("Der Ordner existiert bereits!")
except FileNotFoundError:
    print("Der angegebene Pfad existiert nicht!")

Der angegebene Pfad existiert nicht!


<div  class="alert alert-block alert-info">
4. Du hast eine Liste mit IDs und eine mit Personen-Informationen, die in Tupeln verpackt sind. Füge die Liste mittels Zip zusammen und mache ein Dictionary namens personen_dict daraus. Lasse dir dann alle Infos zur Person mit der ID 4 ausgeben. Dein Output sollte so aussehen:

    Output:
    Name: Diana
    Alter: 29
    Adresse: Philosophenweg 7, Heidelberg
(8 Punkte)
</div>

In [38]:
ids = [1, 2, 3, 4, 5]
personen_infos = [("Alice", 23, "Am Waldrand 12, Stendal"), ("Bob", 35, "Bahnhofstr. 12, Berlin"), ("Charlie", 47, "Kühnstraße 32, Hamburg"), ("Diana", 29, "Philosophenweg 7, Heidelberg"), ("Eve", 19, "Gellertstraße 15, Frankfurt am Main")]

In [39]:
leute_dict = dict(zip(ids, personen_infos))

In [40]:
print("Name: " + leute_dict[4][0])
print("Alter: " + str(leute_dict[4][1]))
print("Adresse: " + leute_dict[4][2])

Name: Diana
Alter: 29
Adresse: Philosophenweg 7, Heidelberg


<div  class="alert alert-block alert-info">
5. Du hast eine Liste mit Beträgen in kanadischen Dollar vorliegen. Du möchtest diese in Euro umrechnen. Ein kanadischer Dollar entspricht dabei 0,68 Euro. Löse mit Mapping und einer Lambda-Funktion. Vergiss nicht auf zwei Nachkommastellen zu runden. Speichere das Ergebnis in ueberweisungen_euro und lass dir die Liste ausgeben. (5 Punkte)
</div>

In [41]:
ueberweisungen = [1927, 2236, 5547, 3566, 7847, 2916, 7587, 7196, 4096, 6056, 4806, 7256, 7553, 7986, 2627, 1618, 3787, 8452, 918, 2399, 4138, 3047, 5675, 7197, 261, 1196, 2156, 2376, 9426, 1723, 7826]

In [42]:
ueberweisungen_euro = list(map(lambda x: round(x*0.68,2), ueberweisungen))
print(ueberweisungen_euro)

[1310.36, 1520.48, 3771.96, 2424.88, 5335.96, 1982.88, 5159.16, 4893.28, 2785.28, 4118.08, 3268.08, 4934.08, 5136.04, 5430.48, 1786.36, 1100.24, 2575.16, 5747.36, 624.24, 1631.32, 2813.84, 2071.96, 3859.0, 4893.96, 177.48, 813.28, 1466.08, 1615.68, 6409.68, 1171.64, 5321.68]


<div  class="alert alert-block alert-info">
6. Nun möchtest du wissen, wie viele Beträge ab 5000 Euro in deiner Liste vorkommen. Filtere deine Liste nach den Beträgen und speichere das Ergebnis in hohe_ueberweisungen. Lasse dir schließlich hohe_ueberweisungen ausgeben und zähle die Menge der Überweisungen mit einer Builtin-Funktion, die du schon länger kennst. (4 Punkte)
</div>

In [43]:
list(filter(lambda x: x >= 5000, ueberweisungen_euro))

[5335.96, 5159.16, 5136.04, 5430.48, 5747.36, 6409.68, 5321.68]

<div  class="alert alert-block alert-info">
7. Erstelle ein zweidimensionales Numpy-Array und wandel es in ein eindimensionales um. (6 Punkte)
</div>

In [1]:
import numpy as np

array1 = np.array([[23,1,3,5],[34,90,7,4]])
print(array1.shape)
array1 = array1.reshape(-1)
print(array1)

(2, 4)
[23  1  3  5 34 90  7  4]


<div  class="alert alert-block alert-info">
8. Lass dir die Dimension des Arrays ausgeben. (3 Punkte)
</div>

In [45]:
print(array1.ndim)

1


<div  class="alert alert-block alert-info">
9. Gegeben ist folgendes Numpy-Array. Füge dieses Array mit dem eindimensionalen Array aus Aufgabe 9 zusammen. Lass dir das Ergebnis ausgeben. (4 Punkte)
</div>

In [46]:
arrayx = np.array([2,1,4])

print(np.concatenate((array1, arrayx)))

[23  1  3  5 34 90  7  4  2  1  4]


<div  class="alert alert-block alert-info">
10. Gegeben ist folgendes Array. Lass dir die Indices ausgeben, an denen sich die Zahl 23 befindet. (6 Punkte)

    Output:
    (array([0, 4, 6], dtype=int64),)
</div>

In [47]:
arrayx2 = np.array([23,42,15,16,23,74,23])

np.where(arrayx2 == 23)

(array([0, 4, 6], dtype=int64),)