<br><br><center><h1 style="font-size:2em;color:#2467C0">Tagesaufgaben 29.03.2022</h1></center>
<br>


# Built-ins und Testing

1. Du hast zwei Listen mit Vor- und Nachnamen. Die zueinander gehörigen Vor- und Nachnamen haben dabei dieselben Index-Positionen. Will heißen: Jonas heißt mit Nachnamen Schneider, David heißt mit Nachnamen Klein usw. Füge die beiden Listen mittels Zip zusammen und erstelle daraus eine Liste mit Tupeln und nenne sie tupel_people. Erstelle außerdem aus dem Zip-Objekt eine Dictionary und nenne es leute_dict.

In [1]:
# Liste mit Vornamen
vornamen = ["Jonas", "David", "Anna", "Isabelle", "Benjamin", "Felix", "Greta", "Isabelle", "Emma", "Hannes"]

# Liste mit Nachnamen
nachnamen = ["Schneider", "Klein", "Hoffmann", "Becker", "Wagner", "Müller", "Fischer", "Bauer", "Brandt", "Schmidt", "Hansen"]

2. Du suchst nach einer Person namens Isabelle Becker. Durchsuche die Tupel-Liste nach ihr. Lasse dir auch ihre Position ausgeben. Zum Knobeln: Versuche sie im leute_dict zu finden. Was ist hier das Problem?

3. Optional: Kannst du die Aufgabe auch ohne den Schritt mit der Liste lösen und direkt mit dem zip-Objekt in einer for-Schleife arbeiten?

4. Du hast ein Kleingewerbe und eine Liste aller Einnahmen aus dem letzten Kalenderjahr. Du möchtest wissen, wie viel du für jeden Auftrag wirklich verdient hast und 14 Prozent Steuer davon abziehen. Löse das mithilfe map und einer Lambda-Funktion und speichere die Liste in die Variabel netto_einkommen. Bitte runde alle Werte auf zwei Nachkommastellen.

In [2]:
einnahmen = [422, 440, 460, 480, 500, 520, 540, 560, 280, 400, 650, 240, 360, 680, 70, 720, 440, 80, 280, 100, 520, 440, 160, 380]

5. Vergleiche nun die Summe deiner Einnahmen und die Summe deiner Netto-Einnahmen. Wie viele Euro musst du an den Staat abdrücken?

6. Du hast eine Zahlenliste. Lasse dir eine Liste mit allen Zahlen ausgeben, die sich durch sieben teilen lassen. Nutze dazu filter!

In [3]:
zahlenliste = [990, 1,60, 79, 431, 154, 453, 322, 84, 765, 321, 633, 542, 105]

7. Du hast Code in Form eines Strings vorliegen. Wenn du die Zelle laufen lässt, kriegst du nicht den erwünschten Output. Behebe das Problem mit eval.

In [4]:
'"Hallo Welt"[6:]'

'"Hallo Welt"[6:]'

8. Bei den Tagesaufgaben liegt eine Datei namens rechner.py mit zwei Rechenoperationen als Funktionen. Schreibe Tests zu diesen Funktionen! (Mindestens drei assertEquals pro Rechenoperation.) Führe die Tests zunächst in Pycharm und später auch über die Kommandozeile aus. Verwende hierzu folgende Schreibweise: python -m unittest name_der_testdatei.py.

# Numpy

<div  class="alert alert-block alert-info">
1. Erstelle ein eindimensionales numpy-Array aus fünf Zahlen
</div>

<div  class="alert alert-block alert-info">
2. Erstelle ein zweidimensionales numpy-Array aus sechs Zahlen
</div>

<div  class="alert alert-block alert-info">
3. Lass dir aus deinem zweidimensionalen Array das erste Array und danach noch die zweite Zahl aus dem ersten Array ausgeben.

    Output:
    [ 3  2 34  5]
    2
</div>

<div  class="alert alert-block alert-info">
4. Lass dir die Anzahl der Dimensionen für die beiden Arrays ausgeben.

    Output:
    1
    2


</div>

<div  class="alert alert-block alert-info">
5. Erstelle ein Array mit zwei Dimensionen, der Form 2,4 und der Größe 8. Lass dir anschließend das Array und all diese Werte ausgeben.

    Output:
    [[ 2  3  1  4]
     [23 34  1  2]]
     2
     (2, 4)
     8
</div>

<div  class="alert alert-block alert-info">
6. Lass dir den Datentypen der Elemente ausgeben, die sich in dem Array aus Aufgabe 5 befinden.

    Output:
    int32
</div>

<div  class="alert alert-block alert-info">
7. Wandel die Elemente des Arrays aus Aufgabe 5 in Floats um.

    Output:
    [[ 2.  3.  1.  4.]
     [23. 34.  1.  2.]]
</div>

<div  class="alert alert-block alert-info">
8. Wandel die Elemente des Arrays aus Aufgabe 5 in Strings um.

    Output:
    [['2' '3' '1' '4']
     ['23' '34' '1' '2']]
</div>